import { writeFile, rm, mkdir, chmod } from "node:fs/promises";
import { join } from "node:path";
import { homedir } from "node:os";
import { createHash } from "node:crypto";
import type { McpDef } from "../manifest/schema.ts";
import { extractKeychainRefs } from "./resolve.ts";
import { parseStdioCommand } from "../harnesses/mcp-util.ts";

const WRAPPERS_DIR = join(homedir(), ".harness-config", "wrappers");

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'"'"'`)}'`;
}

function requireEnvName(name: string): string {
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) {
    throw new Error(`Invalid environment variable name for keychain wrapper: ${name}`);
  }
  return name;
}

/**
 * Get the path where a wrapper script would be generated for a server.
 */
export function getWrapperPath(serverName: string, def?: McpDef): string {
  const safeName = serverName.replace(/[^a-zA-Z0-9_-]/g, "-");
  const suffix = def
    ? `-${createHash("sha256").update(JSON.stringify(def)).digest("hex").slice(0, 12)}`
    : "";
  return join(WRAPPERS_DIR, `${safeName}${suffix}.sh`);
}

/**
 * Generate a keychain wrapper script for a stdio MCP server.
 * The wrapper:
 * 1. Resolves credentials from macOS Keychain
 * 2. Exports them as environment variables
 * 3. exec's the real MCP server command
 */
export async function generateWrapper(
  serverName: string,
  def: McpDef & { stdio: string | string[] },
): Promise<string> {
  const keychainRefs = extractKeychainRefs(def);
  const { command, args } = parseStdioCommand(def.stdio);
  const wrapperPath = getWrapperPath(serverName, def);

  const exportLines = Object.entries(keychainRefs)
    .map(
      ([varName, service]) =>
        `export ${requireEnvName(varName)}="$(security find-generic-password -s ${shellQuote(service)} -a "$USER" -w)"`,
    )
    .join("\n");

  // Also pass through any non-keychain env vars (not possible per schema, but defensive)
  const passthroughLines: string[] = [];
  if (def.env) {
    for (const item of def.env) {
      if (typeof item === "string") {
        // Bare passthrough — no need to export, already in environment
        continue;
      }
      // All key-value pairs are keychain: refs (validated by schema)
    }
  }

  const allExports = [exportLines, ...passthroughLines].filter(Boolean).join("\n");

  const quotedArgs = args.map(shellQuote).join(" ");
  const execLine = quotedArgs
    ? `exec ${shellQuote(command)} ${quotedArgs}`
    : `exec ${shellQuote(command)}`;

  const script = `#!/bin/bash
# Auto-generated by harness-config — do not edit
# Server: ${serverName.replace(/[\r\n]/g, " ")}
# Generated: ${new Date().toISOString()}

set -euo pipefail

${allExports}

${execLine}
`;

  await mkdir(WRAPPERS_DIR, { recursive: true });
  await writeFile(wrapperPath, script, "utf-8");
  await chmod(wrapperPath, 0o755);

  return wrapperPath;
}

/**
 * Remove a wrapper script for a server.
 */
export async function removeWrapper(serverName: string): Promise<boolean> {
  const wrapperPath = getWrapperPath(serverName);
  try {
    await rm(wrapperPath);
    return true;
  } catch (err: any) {
    if (err.code === "ENOENT") return false;
    throw err;
  }
}

/**
 * Generate wrappers for all servers that need them.
 * Returns a map of server name → wrapper path.
 */
export async function generateWrappers(
  mcps: Record<string, McpDef>,
): Promise<Record<string, string>> {
  const wrapperPaths: Record<string, string> = {};

  for (const [name, def] of Object.entries(mcps)) {
    if ("stdio" in def && def.stdio) {
      const keychainRefs = extractKeychainRefs(def);
      if (Object.keys(keychainRefs).length > 0) {
        const path = await generateWrapper(name, def as McpDef & { stdio: string | string[] });
        wrapperPaths[name] = path;
      }
    }
  }

  return wrapperPaths;
}

/**
 * Remove all wrappers for a list of server names.
 */
export async function removeWrappers(serverNames: string[]): Promise<void> {
  for (const name of serverNames) {
    await removeWrapper(name);
  }
}
